tunnel: <TUNNEL_UUID>
credentials-file: C:\Users\<USER>\.cloudflared\<TUNNEL_UUID>.json

ingress:
  - hostname: filmclub.spoon.studio
    service: http://127.0.0.1:3000
  - hostname: api.spoon.studio
    service: http://127.0.0.1:4000
  - service: http_status:404

