services:
  postgres:
    image: postgres:16
    container_name: filmclub-postgres
    environment:
      POSTGRES_USER: filmclub
      POSTGRES_PASSWORD: filmclub
      POSTGRES_DB: filmclub
    ports:
      - "55432:5432"
    volumes:
      - filmclub_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: filmclub-redis
    ports:
      - "6379:6379"
    volumes:
      - filmclub_redis_data:/data

volumes:
  filmclub_pg_data:
  filmclub_redis_data:
